name: Test Formula

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - ubuntu-24.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@master
      - name: Check tap syntax
        run: brew test-bot --only-tap-syntax
      - name: Tap checkout
        run: brew tap hust-open-atom-club/tap "$GITHUB_WORKSPACE"
      - name: Install formula
        run: brew install hust-open-atom-club/tap/atomgit-cli
      - name: Test formula
        run: brew test hust-open-atom-club/tap/atomgit-cli
      - name: Verify executable
        run: ag version
